//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: aeon
// ----------------------------------------------------------------------------
pub mod aeon {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for aeon
    pub fn program_id() -> Pubkey {
        pubkey!("8i5E3R2to4R57TEPFs5DmxhDMAUUvWcXjFZup6MnCMEn")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: InitializeConfig
    // ....................................................................

    /// Main instruction struct for InitializeConfig
    pub struct InitializeConfigInstruction {
        pub accounts: InitializeConfigInstructionAccountMetas,
        pub data: InitializeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeConfigInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeConfigInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub system_program: Pubkey,
    }

    impl InitializeConfigInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey, system_program: Pubkey) -> Self {
            Self {
                admin,

                config,

                system_program,
            }
        }
    }

    /// Instruction data for InitializeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeConfigInstructionData {
        pub aeon_mint: Pubkey,
    }

    impl InitializeConfigInstructionData {
        pub fn new(aeon_mint: Pubkey) -> Self {
            Self { aeon_mint }
        }
    }

    /// Implementation for InitializeConfigInstruction
    impl InitializeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [208u8, 127u8, 21u8, 1u8, 194u8, 190u8, 196u8, 70u8]
        }

        pub fn data(data: InitializeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeConfigInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(accounts.system_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RegisterAgent
    // ....................................................................

    /// Main instruction struct for RegisterAgent
    pub struct RegisterAgentInstruction {
        pub accounts: RegisterAgentInstructionAccountMetas,
        pub data: RegisterAgentInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RegisterAgent instruction
    #[derive(Debug, Clone, Default)]
    pub struct RegisterAgentInstructionAccountMetas {
        pub agent: AccountMeta,

        pub config: AccountMeta,

        pub agent_identity: AccountMeta,

        pub cri: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RegisterAgent instruction
    #[derive(Debug, Clone)]
    pub struct RegisterAgentInstructionAccounts {
        pub agent: Pubkey,

        pub config: Pubkey,

        pub agent_identity: Pubkey,

        pub cri: Pubkey,

        pub system_program: Pubkey,
    }

    impl RegisterAgentInstructionAccounts {
        pub fn new(
            agent: Pubkey,

            config: Pubkey,

            agent_identity: Pubkey,

            cri: Pubkey,

            system_program: Pubkey,
        ) -> Self {
            Self {
                agent,

                config,

                agent_identity,

                cri,

                system_program,
            }
        }
    }

    /// Instruction data for RegisterAgent
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RegisterAgentInstructionData {}

    impl RegisterAgentInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RegisterAgentInstruction
    impl RegisterAgentInstruction {
        fn discriminator() -> [u8; 8] {
            [135u8, 157u8, 66u8, 195u8, 2u8, 113u8, 175u8, 30u8]
        }

        pub fn data(data: RegisterAgentInstructionData) -> Self {
            Self {
                accounts: RegisterAgentInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RegisterAgentInstructionAccounts) -> Self {
            self.accounts.agent = AccountMeta::new(accounts.agent, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.agent_identity = AccountMeta::new(accounts.agent_identity, false);

            self.accounts.cri = AccountMeta::new(accounts.cri, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(accounts.system_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.agent.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.agent_identity.clone());

            metas.push(self.accounts.cri.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: IssueAuthority
    // ....................................................................

    /// Main instruction struct for IssueAuthority
    pub struct IssueAuthorityInstruction {
        pub accounts: IssueAuthorityInstructionAccountMetas,
        pub data: IssueAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for IssueAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct IssueAuthorityInstructionAccountMetas {
        pub agent: AccountMeta,

        pub config: AccountMeta,

        pub agent_identity: AccountMeta,

        pub parent_authority: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for IssueAuthority instruction
    #[derive(Debug, Clone)]
    pub struct IssueAuthorityInstructionAccounts {
        pub agent: Pubkey,

        pub config: Pubkey,

        pub agent_identity: Pubkey,

        pub parent_authority: Pubkey,

        pub authority: Pubkey,

        pub system_program: Pubkey,
    }

    impl IssueAuthorityInstructionAccounts {
        pub fn new(
            agent: Pubkey,

            config: Pubkey,

            agent_identity: Pubkey,

            parent_authority: Pubkey,

            authority: Pubkey,

            system_program: Pubkey,
        ) -> Self {
            Self {
                agent,

                config,

                agent_identity,

                parent_authority,

                authority,

                system_program,
            }
        }
    }

    /// Instruction data for IssueAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct IssueAuthorityInstructionData {
        pub authority_id: u64,

        pub budget: u64,

        pub max_per_tx: u64,

        pub max_total: u64,

        pub categories: Vec<[u8; 16]>,

        pub parent_id: u64,

        pub expiry_slot: u64,
    }

    impl IssueAuthorityInstructionData {
        pub fn new(
            authority_id: u64,

            budget: u64,

            max_per_tx: u64,

            max_total: u64,

            categories: Vec<[u8; 16]>,

            parent_id: u64,

            expiry_slot: u64,
        ) -> Self {
            Self {
                authority_id,

                budget,

                max_per_tx,

                max_total,

                categories,

                parent_id,

                expiry_slot,
            }
        }
    }

    /// Implementation for IssueAuthorityInstruction
    impl IssueAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [46u8, 62u8, 161u8, 139u8, 184u8, 96u8, 84u8, 23u8]
        }

        pub fn data(data: IssueAuthorityInstructionData) -> Self {
            Self {
                accounts: IssueAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: IssueAuthorityInstructionAccounts) -> Self {
            self.accounts.agent = AccountMeta::new(accounts.agent, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.agent_identity =
                AccountMeta::new_readonly(accounts.agent_identity, false);

            self.accounts.parent_authority =
                AccountMeta::new_readonly(accounts.parent_authority, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(accounts.system_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.agent.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.agent_identity.clone());

            metas.push(self.accounts.parent_authority.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RevokeAuthority
    // ....................................................................

    /// Main instruction struct for RevokeAuthority
    pub struct RevokeAuthorityInstruction {
        pub accounts: RevokeAuthorityInstructionAccountMetas,
        pub data: RevokeAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RevokeAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct RevokeAuthorityInstructionAccountMetas {
        pub agent: AccountMeta,

        pub config: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for RevokeAuthority instruction
    #[derive(Debug, Clone)]
    pub struct RevokeAuthorityInstructionAccounts {
        pub agent: Pubkey,

        pub config: Pubkey,

        pub authority: Pubkey,
    }

    impl RevokeAuthorityInstructionAccounts {
        pub fn new(agent: Pubkey, config: Pubkey, authority: Pubkey) -> Self {
            Self {
                agent,

                config,

                authority,
            }
        }
    }

    /// Instruction data for RevokeAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RevokeAuthorityInstructionData {
        pub authority_id: u64,
    }

    impl RevokeAuthorityInstructionData {
        pub fn new(authority_id: u64) -> Self {
            Self { authority_id }
        }
    }

    /// Implementation for RevokeAuthorityInstruction
    impl RevokeAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [233u8, 254u8, 239u8, 15u8, 49u8, 183u8, 105u8, 21u8]
        }

        pub fn data(data: RevokeAuthorityInstructionData) -> Self {
            Self {
                accounts: RevokeAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RevokeAuthorityInstructionAccounts) -> Self {
            self.accounts.agent = AccountMeta::new_readonly(accounts.agent, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.agent.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pay
    // ....................................................................

    /// Main instruction struct for Pay
    pub struct PayInstruction {
        pub accounts: PayInstructionAccountMetas,
        pub data: PayInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pay instruction
    #[derive(Debug, Clone, Default)]
    pub struct PayInstructionAccountMetas {
        pub payer: AccountMeta,

        pub payee: AccountMeta,

        pub config: AccountMeta,

        pub authority: AccountMeta,

        pub payer_cri: AccountMeta,

        pub payee_cri: AccountMeta,

        pub payer_token: AccountMeta,

        pub payee_token: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Pay instruction
    #[derive(Debug, Clone)]
    pub struct PayInstructionAccounts {
        pub payer: Pubkey,

        pub payee: Pubkey,

        pub config: Pubkey,

        pub authority: Pubkey,

        pub payer_cri: Pubkey,

        pub payee_cri: Pubkey,

        pub payer_token: Pubkey,

        pub payee_token: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl PayInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            payee: Pubkey,

            config: Pubkey,

            authority: Pubkey,

            payer_cri: Pubkey,

            payee_cri: Pubkey,

            payer_token: Pubkey,

            payee_token: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                payer,

                payee,

                config,

                authority,

                payer_cri,

                payee_cri,

                payer_token,

                payee_token,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for Pay
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PayInstructionData {
        pub amount: u64,

        pub authority_id: u64,

        pub category: [u8; 16],
    }

    impl PayInstructionData {
        pub fn new(amount: u64, authority_id: u64, category: [u8; 16]) -> Self {
            Self {
                amount,

                authority_id,

                category,
            }
        }
    }

    /// Implementation for PayInstruction
    impl PayInstruction {
        fn discriminator() -> [u8; 8] {
            [119u8, 18u8, 216u8, 65u8, 192u8, 117u8, 122u8, 220u8]
        }

        pub fn data(data: PayInstructionData) -> Self {
            Self {
                accounts: PayInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PayInstructionAccounts) -> Self {
            self.accounts.payer = AccountMeta::new_readonly(accounts.payer, true);

            self.accounts.payee = AccountMeta::new_readonly(accounts.payee, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, false);

            self.accounts.payer_cri = AccountMeta::new(accounts.payer_cri, false);

            self.accounts.payee_cri = AccountMeta::new(accounts.payee_cri, false);

            self.accounts.payer_token = AccountMeta::new(accounts.payer_token, false);

            self.accounts.payee_token = AccountMeta::new(accounts.payee_token, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.payee.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer_cri.clone());

            metas.push(self.accounts.payee_cri.clone());

            metas.push(self.accounts.payer_token.clone());

            metas.push(self.accounts.payee_token.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateEscrow
    // ....................................................................

    /// Main instruction struct for CreateEscrow
    pub struct CreateEscrowInstruction {
        pub accounts: CreateEscrowInstructionAccountMetas,
        pub data: CreateEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateEscrowInstructionAccountMetas {
        pub payer: AccountMeta,

        pub payee: AccountMeta,

        pub config: AccountMeta,

        pub authority: AccountMeta,

        pub escrow: AccountMeta,

        pub escrow_vault: AccountMeta,

        pub payer_token: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreateEscrow instruction
    #[derive(Debug, Clone)]
    pub struct CreateEscrowInstructionAccounts {
        pub payer: Pubkey,

        pub payee: Pubkey,

        pub config: Pubkey,

        pub authority: Pubkey,

        pub escrow: Pubkey,

        pub escrow_vault: Pubkey,

        pub payer_token: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,

        pub system_program: Pubkey,

        pub rent: Pubkey,
    }

    impl CreateEscrowInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            payee: Pubkey,

            config: Pubkey,

            authority: Pubkey,

            escrow: Pubkey,

            escrow_vault: Pubkey,

            payer_token: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,

            system_program: Pubkey,

            rent: Pubkey,
        ) -> Self {
            Self {
                payer,

                payee,

                config,

                authority,

                escrow,

                escrow_vault,

                payer_token,

                aeon_mint,

                token_program,

                system_program,

                rent,
            }
        }
    }

    /// Instruction data for CreateEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateEscrowInstructionData {
        pub escrow_id: u64,

        pub amount: u64,

        pub authority_id: u64,

        pub category: [u8; 16],

        pub condition_type: u8,

        pub condition_data: [u8; 64],

        pub expiry_slot: u64,
    }

    impl CreateEscrowInstructionData {
        pub fn new(
            escrow_id: u64,

            amount: u64,

            authority_id: u64,

            category: [u8; 16],

            condition_type: u8,

            condition_data: [u8; 64],

            expiry_slot: u64,
        ) -> Self {
            Self {
                escrow_id,

                amount,

                authority_id,

                category,

                condition_type,

                condition_data,

                expiry_slot,
            }
        }
    }

    /// Implementation for CreateEscrowInstruction
    impl CreateEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 215u8, 165u8, 116u8, 36u8, 108u8, 68u8, 80u8]
        }

        pub fn data(data: CreateEscrowInstructionData) -> Self {
            Self {
                accounts: CreateEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateEscrowInstructionAccounts) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.payee = AccountMeta::new_readonly(accounts.payee, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, false);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.escrow_vault = AccountMeta::new(accounts.escrow_vault, false);

            self.accounts.payer_token = AccountMeta::new(accounts.payer_token, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(accounts.system_program, false);

            self.accounts.rent = AccountMeta::new_readonly(accounts.rent, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.payee.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.escrow_vault.clone());

            metas.push(self.accounts.payer_token.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ReleaseEscrow
    // ....................................................................

    /// Main instruction struct for ReleaseEscrow
    pub struct ReleaseEscrowInstruction {
        pub accounts: ReleaseEscrowInstructionAccountMetas,
        pub data: ReleaseEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ReleaseEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct ReleaseEscrowInstructionAccountMetas {
        pub releaser: AccountMeta,

        pub escrow: AccountMeta,

        pub escrow_vault: AccountMeta,

        pub payee_token: AccountMeta,

        pub payer_cri: AccountMeta,

        pub payee_cri: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ReleaseEscrow instruction
    #[derive(Debug, Clone)]
    pub struct ReleaseEscrowInstructionAccounts {
        pub releaser: Pubkey,

        pub escrow: Pubkey,

        pub escrow_vault: Pubkey,

        pub payee_token: Pubkey,

        pub payer_cri: Pubkey,

        pub payee_cri: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl ReleaseEscrowInstructionAccounts {
        pub fn new(
            releaser: Pubkey,

            escrow: Pubkey,

            escrow_vault: Pubkey,

            payee_token: Pubkey,

            payer_cri: Pubkey,

            payee_cri: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                releaser,

                escrow,

                escrow_vault,

                payee_token,

                payer_cri,

                payee_cri,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for ReleaseEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ReleaseEscrowInstructionData {
        pub escrow_id: u64,

        pub witness: [u8; 64],
    }

    impl ReleaseEscrowInstructionData {
        pub fn new(escrow_id: u64, witness: [u8; 64]) -> Self {
            Self { escrow_id, witness }
        }
    }

    /// Implementation for ReleaseEscrowInstruction
    impl ReleaseEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [146u8, 253u8, 129u8, 233u8, 20u8, 145u8, 181u8, 206u8]
        }

        pub fn data(data: ReleaseEscrowInstructionData) -> Self {
            Self {
                accounts: ReleaseEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ReleaseEscrowInstructionAccounts) -> Self {
            self.accounts.releaser = AccountMeta::new_readonly(accounts.releaser, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.escrow_vault = AccountMeta::new(accounts.escrow_vault, false);

            self.accounts.payee_token = AccountMeta::new(accounts.payee_token, false);

            self.accounts.payer_cri = AccountMeta::new(accounts.payer_cri, false);

            self.accounts.payee_cri = AccountMeta::new(accounts.payee_cri, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.releaser.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.escrow_vault.clone());

            metas.push(self.accounts.payee_token.clone());

            metas.push(self.accounts.payer_cri.clone());

            metas.push(self.accounts.payee_cri.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelEscrow
    // ....................................................................

    /// Main instruction struct for CancelEscrow
    pub struct CancelEscrowInstruction {
        pub accounts: CancelEscrowInstructionAccountMetas,
        pub data: CancelEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelEscrowInstructionAccountMetas {
        pub canceller: AccountMeta,

        pub escrow: AccountMeta,

        pub escrow_vault: AccountMeta,

        pub payer_token: AccountMeta,

        pub payer_cri: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CancelEscrow instruction
    #[derive(Debug, Clone)]
    pub struct CancelEscrowInstructionAccounts {
        pub canceller: Pubkey,

        pub escrow: Pubkey,

        pub escrow_vault: Pubkey,

        pub payer_token: Pubkey,

        pub payer_cri: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl CancelEscrowInstructionAccounts {
        pub fn new(
            canceller: Pubkey,

            escrow: Pubkey,

            escrow_vault: Pubkey,

            payer_token: Pubkey,

            payer_cri: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                canceller,

                escrow,

                escrow_vault,

                payer_token,

                payer_cri,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for CancelEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelEscrowInstructionData {
        pub escrow_id: u64,
    }

    impl CancelEscrowInstructionData {
        pub fn new(escrow_id: u64) -> Self {
            Self { escrow_id }
        }
    }

    /// Implementation for CancelEscrowInstruction
    impl CancelEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [156u8, 203u8, 54u8, 179u8, 38u8, 72u8, 33u8, 21u8]
        }

        pub fn data(data: CancelEscrowInstructionData) -> Self {
            Self {
                accounts: CancelEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelEscrowInstructionAccounts) -> Self {
            self.accounts.canceller = AccountMeta::new_readonly(accounts.canceller, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.escrow_vault = AccountMeta::new(accounts.escrow_vault, false);

            self.accounts.payer_token = AccountMeta::new(accounts.payer_token, false);

            self.accounts.payer_cri = AccountMeta::new(accounts.payer_cri, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.canceller.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.escrow_vault.clone());

            metas.push(self.accounts.payer_token.clone());

            metas.push(self.accounts.payer_cri.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AtomicSplit
    // ....................................................................

    /// Main instruction struct for AtomicSplit
    pub struct AtomicSplitInstruction {
        pub accounts: AtomicSplitInstructionAccountMetas,
        pub data: AtomicSplitInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AtomicSplit instruction
    #[derive(Debug, Clone, Default)]
    pub struct AtomicSplitInstructionAccountMetas {
        pub payer: AccountMeta,

        pub payee_a: AccountMeta,

        pub payee_b: AccountMeta,

        pub config: AccountMeta,

        pub authority: AccountMeta,

        pub payer_token: AccountMeta,

        pub payee_a_token: AccountMeta,

        pub payee_b_token: AccountMeta,

        pub payer_cri: AccountMeta,

        pub payee_a_cri: AccountMeta,

        pub payee_b_cri: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for AtomicSplit instruction
    #[derive(Debug, Clone)]
    pub struct AtomicSplitInstructionAccounts {
        pub payer: Pubkey,

        pub payee_a: Pubkey,

        pub payee_b: Pubkey,

        pub config: Pubkey,

        pub authority: Pubkey,

        pub payer_token: Pubkey,

        pub payee_a_token: Pubkey,

        pub payee_b_token: Pubkey,

        pub payer_cri: Pubkey,

        pub payee_a_cri: Pubkey,

        pub payee_b_cri: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl AtomicSplitInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            payee_a: Pubkey,

            payee_b: Pubkey,

            config: Pubkey,

            authority: Pubkey,

            payer_token: Pubkey,

            payee_a_token: Pubkey,

            payee_b_token: Pubkey,

            payer_cri: Pubkey,

            payee_a_cri: Pubkey,

            payee_b_cri: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                payer,

                payee_a,

                payee_b,

                config,

                authority,

                payer_token,

                payee_a_token,

                payee_b_token,

                payer_cri,

                payee_a_cri,

                payee_b_cri,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for AtomicSplit
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AtomicSplitInstructionData {
        pub authority_id: u64,

        pub amounts: Vec<u64>,

        pub category: [u8; 16],
    }

    impl AtomicSplitInstructionData {
        pub fn new(authority_id: u64, amounts: Vec<u64>, category: [u8; 16]) -> Self {
            Self {
                authority_id,

                amounts,

                category,
            }
        }
    }

    /// Implementation for AtomicSplitInstruction
    impl AtomicSplitInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 8u8, 165u8, 93u8, 2u8, 50u8, 35u8, 231u8]
        }

        pub fn data(data: AtomicSplitInstructionData) -> Self {
            Self {
                accounts: AtomicSplitInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AtomicSplitInstructionAccounts) -> Self {
            self.accounts.payer = AccountMeta::new_readonly(accounts.payer, true);

            self.accounts.payee_a = AccountMeta::new_readonly(accounts.payee_a, false);

            self.accounts.payee_b = AccountMeta::new_readonly(accounts.payee_b, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, false);

            self.accounts.payer_token = AccountMeta::new(accounts.payer_token, false);

            self.accounts.payee_a_token = AccountMeta::new(accounts.payee_a_token, false);

            self.accounts.payee_b_token = AccountMeta::new(accounts.payee_b_token, false);

            self.accounts.payer_cri = AccountMeta::new(accounts.payer_cri, false);

            self.accounts.payee_a_cri = AccountMeta::new(accounts.payee_a_cri, false);

            self.accounts.payee_b_cri = AccountMeta::new(accounts.payee_b_cri, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.payee_a.clone());

            metas.push(self.accounts.payee_b.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer_token.clone());

            metas.push(self.accounts.payee_a_token.clone());

            metas.push(self.accounts.payee_b_token.clone());

            metas.push(self.accounts.payer_cri.clone());

            metas.push(self.accounts.payee_a_cri.clone());

            metas.push(self.accounts.payee_b_cri.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateOrg
    // ....................................................................

    /// Main instruction struct for CreateOrg
    pub struct CreateOrgInstruction {
        pub accounts: CreateOrgInstructionAccountMetas,
        pub data: CreateOrgInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateOrg instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateOrgInstructionAccountMetas {
        pub creator: AccountMeta,

        pub config: AccountMeta,

        pub creator_identity: AccountMeta,

        pub organization: AccountMeta,

        pub org_treasury: AccountMeta,

        pub creator_member: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreateOrg instruction
    #[derive(Debug, Clone)]
    pub struct CreateOrgInstructionAccounts {
        pub creator: Pubkey,

        pub config: Pubkey,

        pub creator_identity: Pubkey,

        pub organization: Pubkey,

        pub org_treasury: Pubkey,

        pub creator_member: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,

        pub system_program: Pubkey,

        pub rent: Pubkey,
    }

    impl CreateOrgInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            config: Pubkey,

            creator_identity: Pubkey,

            organization: Pubkey,

            org_treasury: Pubkey,

            creator_member: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,

            system_program: Pubkey,

            rent: Pubkey,
        ) -> Self {
            Self {
                creator,

                config,

                creator_identity,

                organization,

                org_treasury,

                creator_member,

                aeon_mint,

                token_program,

                system_program,

                rent,
            }
        }
    }

    /// Instruction data for CreateOrg
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateOrgInstructionData {
        pub org_id: u64,

        pub name_hash: [u8; 32],

        pub creator_share_bps: u16,
    }

    impl CreateOrgInstructionData {
        pub fn new(org_id: u64, name_hash: [u8; 32], creator_share_bps: u16) -> Self {
            Self {
                org_id,

                name_hash,

                creator_share_bps,
            }
        }
    }

    /// Implementation for CreateOrgInstruction
    impl CreateOrgInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 115u8, 187u8, 249u8, 36u8, 3u8, 186u8, 175u8]
        }

        pub fn data(data: CreateOrgInstructionData) -> Self {
            Self {
                accounts: CreateOrgInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateOrgInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.creator_identity =
                AccountMeta::new_readonly(accounts.creator_identity, false);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.org_treasury = AccountMeta::new(accounts.org_treasury, false);

            self.accounts.creator_member = AccountMeta::new(accounts.creator_member, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(accounts.system_program, false);

            self.accounts.rent = AccountMeta::new_readonly(accounts.rent, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.creator_identity.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.org_treasury.clone());

            metas.push(self.accounts.creator_member.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositToOrg
    // ....................................................................

    /// Main instruction struct for DepositToOrg
    pub struct DepositToOrgInstruction {
        pub accounts: DepositToOrgInstructionAccountMetas,
        pub data: DepositToOrgInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositToOrg instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositToOrgInstructionAccountMetas {
        pub member: AccountMeta,

        pub organization: AccountMeta,

        pub org_member: AccountMeta,

        pub org_treasury: AccountMeta,

        pub member_token: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for DepositToOrg instruction
    #[derive(Debug, Clone)]
    pub struct DepositToOrgInstructionAccounts {
        pub member: Pubkey,

        pub organization: Pubkey,

        pub org_member: Pubkey,

        pub org_treasury: Pubkey,

        pub member_token: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl DepositToOrgInstructionAccounts {
        pub fn new(
            member: Pubkey,

            organization: Pubkey,

            org_member: Pubkey,

            org_treasury: Pubkey,

            member_token: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                member,

                organization,

                org_member,

                org_treasury,

                member_token,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for DepositToOrg
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositToOrgInstructionData {
        pub org_id: u64,

        pub amount: u64,
    }

    impl DepositToOrgInstructionData {
        pub fn new(org_id: u64, amount: u64) -> Self {
            Self { org_id, amount }
        }
    }

    /// Implementation for DepositToOrgInstruction
    impl DepositToOrgInstruction {
        fn discriminator() -> [u8; 8] {
            [20u8, 39u8, 3u8, 24u8, 191u8, 146u8, 173u8, 32u8]
        }

        pub fn data(data: DepositToOrgInstructionData) -> Self {
            Self {
                accounts: DepositToOrgInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositToOrgInstructionAccounts) -> Self {
            self.accounts.member = AccountMeta::new_readonly(accounts.member, true);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.org_member = AccountMeta::new_readonly(accounts.org_member, false);

            self.accounts.org_treasury = AccountMeta::new(accounts.org_treasury, false);

            self.accounts.member_token = AccountMeta::new(accounts.member_token, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.member.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.org_member.clone());

            metas.push(self.accounts.org_treasury.clone());

            metas.push(self.accounts.member_token.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: OrgSplit
    // ....................................................................

    /// Main instruction struct for OrgSplit
    pub struct OrgSplitInstruction {
        pub accounts: OrgSplitInstructionAccountMetas,
        pub data: OrgSplitInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for OrgSplit instruction
    #[derive(Debug, Clone, Default)]
    pub struct OrgSplitInstructionAccountMetas {
        pub admin: AccountMeta,

        pub organization: AccountMeta,

        pub admin_member: AccountMeta,

        pub recipient_member: AccountMeta,

        pub recipient_token: AccountMeta,

        pub org_treasury: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for OrgSplit instruction
    #[derive(Debug, Clone)]
    pub struct OrgSplitInstructionAccounts {
        pub admin: Pubkey,

        pub organization: Pubkey,

        pub admin_member: Pubkey,

        pub recipient_member: Pubkey,

        pub recipient_token: Pubkey,

        pub org_treasury: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl OrgSplitInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            organization: Pubkey,

            admin_member: Pubkey,

            recipient_member: Pubkey,

            recipient_token: Pubkey,

            org_treasury: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                admin,

                organization,

                admin_member,

                recipient_member,

                recipient_token,

                org_treasury,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for OrgSplit
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct OrgSplitInstructionData {
        pub org_id: u64,

        pub amounts: Vec<u64>,
    }

    impl OrgSplitInstructionData {
        pub fn new(org_id: u64, amounts: Vec<u64>) -> Self {
            Self { org_id, amounts }
        }
    }

    /// Implementation for OrgSplitInstruction
    impl OrgSplitInstruction {
        fn discriminator() -> [u8; 8] {
            [100u8, 227u8, 62u8, 222u8, 189u8, 106u8, 19u8, 24u8]
        }

        pub fn data(data: OrgSplitInstructionData) -> Self {
            Self {
                accounts: OrgSplitInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: OrgSplitInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.admin_member = AccountMeta::new_readonly(accounts.admin_member, false);

            self.accounts.recipient_member =
                AccountMeta::new_readonly(accounts.recipient_member, false);

            self.accounts.recipient_token = AccountMeta::new(accounts.recipient_token, false);

            self.accounts.org_treasury = AccountMeta::new(accounts.org_treasury, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.admin_member.clone());

            metas.push(self.accounts.recipient_member.clone());

            metas.push(self.accounts.recipient_token.clone());

            metas.push(self.accounts.org_treasury.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DissolveOrg
    // ....................................................................

    /// Main instruction struct for DissolveOrg
    pub struct DissolveOrgInstruction {
        pub accounts: DissolveOrgInstructionAccountMetas,
        pub data: DissolveOrgInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DissolveOrg instruction
    #[derive(Debug, Clone, Default)]
    pub struct DissolveOrgInstructionAccountMetas {
        pub admin: AccountMeta,

        pub organization: AccountMeta,

        pub admin_member: AccountMeta,

        pub admin_token: AccountMeta,

        pub member_b: AccountMeta,

        pub member_b_token: AccountMeta,

        pub org_treasury: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for DissolveOrg instruction
    #[derive(Debug, Clone)]
    pub struct DissolveOrgInstructionAccounts {
        pub admin: Pubkey,

        pub organization: Pubkey,

        pub admin_member: Pubkey,

        pub admin_token: Pubkey,

        pub member_b: Pubkey,

        pub member_b_token: Pubkey,

        pub org_treasury: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl DissolveOrgInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            organization: Pubkey,

            admin_member: Pubkey,

            admin_token: Pubkey,

            member_b: Pubkey,

            member_b_token: Pubkey,

            org_treasury: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                admin,

                organization,

                admin_member,

                admin_token,

                member_b,

                member_b_token,

                org_treasury,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for DissolveOrg
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DissolveOrgInstructionData {
        pub org_id: u64,
    }

    impl DissolveOrgInstructionData {
        pub fn new(org_id: u64) -> Self {
            Self { org_id }
        }
    }

    /// Implementation for DissolveOrgInstruction
    impl DissolveOrgInstruction {
        fn discriminator() -> [u8; 8] {
            [143u8, 107u8, 214u8, 170u8, 100u8, 0u8, 213u8, 54u8]
        }

        pub fn data(data: DissolveOrgInstructionData) -> Self {
            Self {
                accounts: DissolveOrgInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DissolveOrgInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.admin_member = AccountMeta::new_readonly(accounts.admin_member, false);

            self.accounts.admin_token = AccountMeta::new(accounts.admin_token, false);

            self.accounts.member_b = AccountMeta::new_readonly(accounts.member_b, false);

            self.accounts.member_b_token = AccountMeta::new(accounts.member_b_token, false);

            self.accounts.org_treasury = AccountMeta::new(accounts.org_treasury, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.admin_member.clone());

            metas.push(self.accounts.admin_token.clone());

            metas.push(self.accounts.member_b.clone());

            metas.push(self.accounts.member_b_token.clone());

            metas.push(self.accounts.org_treasury.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: JoinOrg
    // ....................................................................

    /// Main instruction struct for JoinOrg
    pub struct JoinOrgInstruction {
        pub accounts: JoinOrgInstructionAccountMetas,
        pub data: JoinOrgInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for JoinOrg instruction
    #[derive(Debug, Clone, Default)]
    pub struct JoinOrgInstructionAccountMetas {
        pub admin: AccountMeta,

        pub new_agent: AccountMeta,

        pub organization: AccountMeta,

        pub admin_member: AccountMeta,

        pub agent_identity: AccountMeta,

        pub new_member: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for JoinOrg instruction
    #[derive(Debug, Clone)]
    pub struct JoinOrgInstructionAccounts {
        pub admin: Pubkey,

        pub new_agent: Pubkey,

        pub organization: Pubkey,

        pub admin_member: Pubkey,

        pub agent_identity: Pubkey,

        pub new_member: Pubkey,

        pub system_program: Pubkey,
    }

    impl JoinOrgInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            new_agent: Pubkey,

            organization: Pubkey,

            admin_member: Pubkey,

            agent_identity: Pubkey,

            new_member: Pubkey,

            system_program: Pubkey,
        ) -> Self {
            Self {
                admin,

                new_agent,

                organization,

                admin_member,

                agent_identity,

                new_member,

                system_program,
            }
        }
    }

    /// Instruction data for JoinOrg
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct JoinOrgInstructionData {
        pub org_id: u64,

        pub role: u8,

        pub share_bps: u16,
    }

    impl JoinOrgInstructionData {
        pub fn new(org_id: u64, role: u8, share_bps: u16) -> Self {
            Self {
                org_id,

                role,

                share_bps,
            }
        }
    }

    /// Implementation for JoinOrgInstruction
    impl JoinOrgInstruction {
        fn discriminator() -> [u8; 8] {
            [109u8, 42u8, 124u8, 13u8, 143u8, 30u8, 147u8, 188u8]
        }

        pub fn data(data: JoinOrgInstructionData) -> Self {
            Self {
                accounts: JoinOrgInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: JoinOrgInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.new_agent = AccountMeta::new_readonly(accounts.new_agent, false);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.admin_member = AccountMeta::new_readonly(accounts.admin_member, false);

            self.accounts.agent_identity =
                AccountMeta::new_readonly(accounts.agent_identity, false);

            self.accounts.new_member = AccountMeta::new(accounts.new_member, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(accounts.system_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.new_agent.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.admin_member.clone());

            metas.push(self.accounts.agent_identity.clone());

            metas.push(self.accounts.new_member.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetMemberShare
    // ....................................................................

    /// Main instruction struct for SetMemberShare
    pub struct SetMemberShareInstruction {
        pub accounts: SetMemberShareInstructionAccountMetas,
        pub data: SetMemberShareInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetMemberShare instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetMemberShareInstructionAccountMetas {
        pub admin: AccountMeta,

        pub organization: AccountMeta,

        pub admin_member: AccountMeta,

        pub target_member: AccountMeta,
    }

    /// Account pubkeys for SetMemberShare instruction
    #[derive(Debug, Clone)]
    pub struct SetMemberShareInstructionAccounts {
        pub admin: Pubkey,

        pub organization: Pubkey,

        pub admin_member: Pubkey,

        pub target_member: Pubkey,
    }

    impl SetMemberShareInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            organization: Pubkey,

            admin_member: Pubkey,

            target_member: Pubkey,
        ) -> Self {
            Self {
                admin,

                organization,

                admin_member,

                target_member,
            }
        }
    }

    /// Instruction data for SetMemberShare
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetMemberShareInstructionData {
        pub org_id: u64,

        pub new_share_bps: u16,
    }

    impl SetMemberShareInstructionData {
        pub fn new(org_id: u64, new_share_bps: u16) -> Self {
            Self {
                org_id,

                new_share_bps,
            }
        }
    }

    /// Implementation for SetMemberShareInstruction
    impl SetMemberShareInstruction {
        fn discriminator() -> [u8; 8] {
            [201u8, 0u8, 164u8, 254u8, 106u8, 117u8, 223u8, 152u8]
        }

        pub fn data(data: SetMemberShareInstructionData) -> Self {
            Self {
                accounts: SetMemberShareInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetMemberShareInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.admin_member = AccountMeta::new_readonly(accounts.admin_member, false);

            self.accounts.target_member = AccountMeta::new(accounts.target_member, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.admin_member.clone());

            metas.push(self.accounts.target_member.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ReclaimOrgResidual
    // ....................................................................

    /// Main instruction struct for ReclaimOrgResidual
    pub struct ReclaimOrgResidualInstruction {
        pub accounts: ReclaimOrgResidualInstructionAccountMetas,
        pub data: ReclaimOrgResidualInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ReclaimOrgResidual instruction
    #[derive(Debug, Clone, Default)]
    pub struct ReclaimOrgResidualInstructionAccountMetas {
        pub authority: AccountMeta,

        pub organization: AccountMeta,

        pub authority_member: AccountMeta,

        pub org_treasury: AccountMeta,

        pub destination: AccountMeta,

        pub aeon_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ReclaimOrgResidual instruction
    #[derive(Debug, Clone)]
    pub struct ReclaimOrgResidualInstructionAccounts {
        pub authority: Pubkey,

        pub organization: Pubkey,

        pub authority_member: Pubkey,

        pub org_treasury: Pubkey,

        pub destination: Pubkey,

        pub aeon_mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl ReclaimOrgResidualInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            organization: Pubkey,

            authority_member: Pubkey,

            org_treasury: Pubkey,

            destination: Pubkey,

            aeon_mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                organization,

                authority_member,

                org_treasury,

                destination,

                aeon_mint,

                token_program,
            }
        }
    }

    /// Instruction data for ReclaimOrgResidual
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ReclaimOrgResidualInstructionData {
        pub org_id: u64,
    }

    impl ReclaimOrgResidualInstructionData {
        pub fn new(org_id: u64) -> Self {
            Self { org_id }
        }
    }

    /// Implementation for ReclaimOrgResidualInstruction
    impl ReclaimOrgResidualInstruction {
        fn discriminator() -> [u8; 8] {
            [238u8, 65u8, 100u8, 177u8, 211u8, 144u8, 234u8, 246u8]
        }

        pub fn data(data: ReclaimOrgResidualInstructionData) -> Self {
            Self {
                accounts: ReclaimOrgResidualInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ReclaimOrgResidualInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.organization = AccountMeta::new(accounts.organization, false);

            self.accounts.authority_member =
                AccountMeta::new_readonly(accounts.authority_member, false);

            self.accounts.org_treasury = AccountMeta::new(accounts.org_treasury, false);

            self.accounts.destination = AccountMeta::new(accounts.destination, false);

            self.accounts.aeon_mint = AccountMeta::new_readonly(accounts.aeon_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.organization.clone());

            metas.push(self.accounts.authority_member.clone());

            metas.push(self.accounts.org_treasury.clone());

            metas.push(self.accounts.destination.clone());

            metas.push(self.accounts.aeon_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub admin: Pubkey,

    pub aeon_mint: Pubkey,

    pub authority_counter: u64,

    pub escrow_counter: u64,

    pub org_counter: u64,

    pub receipt_counter: u64,

    pub min_solvency_bps: u16,

    pub paused: bool,

    pub bump: u8,
}

impl Config {
    pub fn new(
        admin: Pubkey,

        aeon_mint: Pubkey,

        authority_counter: u64,

        escrow_counter: u64,

        org_counter: u64,

        receipt_counter: u64,

        min_solvency_bps: u16,

        paused: bool,

        bump: u8,
    ) -> Self {
        Self {
            admin,

            aeon_mint,

            authority_counter,

            escrow_counter,

            org_counter,

            receipt_counter,

            min_solvency_bps,

            paused,

            bump,
        }
    }
}

/// Custom struct: AgentIdentity
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AgentIdentity {
    pub agent: Pubkey,

    pub created_slot: u64,

    pub active: bool,

    pub metadata_uri_hash: [u8; 32],

    pub bump: u8,
}

impl AgentIdentity {
    pub fn new(
        agent: Pubkey,

        created_slot: u64,

        active: bool,

        metadata_uri_hash: [u8; 32],

        bump: u8,
    ) -> Self {
        Self {
            agent,

            created_slot,

            active,

            metadata_uri_hash,

            bump,
        }
    }
}

/// Custom struct: Cri
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Cri {
    pub agent: Pubkey,

    pub successful_settlements: u64,

    pub failed_settlements: u64,

    pub successful_commitments: u64,

    pub failed_commitments: u64,

    pub volume_settled: u64,

    pub last_active_slot: u64,

    pub created_slot: u64,

    pub bump: u8,
}

impl Cri {
    pub fn new(
        agent: Pubkey,

        successful_settlements: u64,

        failed_settlements: u64,

        successful_commitments: u64,

        failed_commitments: u64,

        volume_settled: u64,

        last_active_slot: u64,

        created_slot: u64,

        bump: u8,
    ) -> Self {
        Self {
            agent,

            successful_settlements,

            failed_settlements,

            successful_commitments,

            failed_commitments,

            volume_settled,

            last_active_slot,

            created_slot,

            bump,
        }
    }
}

/// Custom struct: Authority
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Authority {
    pub authority_id: u64,

    pub agent: Pubkey,

    pub parent_id: u64,

    pub depth: u8,

    pub budget: u64,

    pub spent: u64,

    pub max_per_tx: u64,

    pub max_total: u64,

    pub category_count: u8,

    pub categories: [[u8; 16]; 8],

    pub blocked_count: u8,

    pub blocked_recipients: [Pubkey; 4],

    pub require_min_reserve: u64,

    pub expiry_slot: u64,

    pub status: u8,

    pub bump: u8,
}

impl Authority {
    pub fn new(
        authority_id: u64,

        agent: Pubkey,

        parent_id: u64,

        depth: u8,

        budget: u64,

        spent: u64,

        max_per_tx: u64,

        max_total: u64,

        category_count: u8,

        categories: [[u8; 16]; 8],

        blocked_count: u8,

        blocked_recipients: [Pubkey; 4],

        require_min_reserve: u64,

        expiry_slot: u64,

        status: u8,

        bump: u8,
    ) -> Self {
        Self {
            authority_id,

            agent,

            parent_id,

            depth,

            budget,

            spent,

            max_per_tx,

            max_total,

            category_count,

            categories,

            blocked_count,

            blocked_recipients,

            require_min_reserve,

            expiry_slot,

            status,

            bump,
        }
    }
}

/// Custom struct: Escrow
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Escrow {
    pub escrow_id: u64,

    pub payer: Pubkey,

    pub payee: Pubkey,

    pub amount: u64,

    pub authority_id: u64,

    pub category: [u8; 16],

    pub condition_type: u8,

    pub condition_data: [u8; 64],

    pub status: u8,

    pub created_slot: u64,

    pub expiry_slot: u64,

    pub vault_bump: u8,

    pub bump: u8,
}

impl Escrow {
    pub fn new(
        escrow_id: u64,

        payer: Pubkey,

        payee: Pubkey,

        amount: u64,

        authority_id: u64,

        category: [u8; 16],

        condition_type: u8,

        condition_data: [u8; 64],

        status: u8,

        created_slot: u64,

        expiry_slot: u64,

        vault_bump: u8,

        bump: u8,
    ) -> Self {
        Self {
            escrow_id,

            payer,

            payee,

            amount,

            authority_id,

            category,

            condition_type,

            condition_data,

            status,

            created_slot,

            expiry_slot,

            vault_bump,

            bump,
        }
    }
}

/// Custom struct: Organization
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Organization {
    pub org_id: u64,

    pub name_hash: [u8; 32],

    pub creator: Pubkey,

    pub member_count: u16,

    pub total_share_bps: u16,

    pub status: u8,

    pub created_slot: u64,

    pub treasury_bump: u8,

    pub bump: u8,
}

impl Organization {
    pub fn new(
        org_id: u64,

        name_hash: [u8; 32],

        creator: Pubkey,

        member_count: u16,

        total_share_bps: u16,

        status: u8,

        created_slot: u64,

        treasury_bump: u8,

        bump: u8,
    ) -> Self {
        Self {
            org_id,

            name_hash,

            creator,

            member_count,

            total_share_bps,

            status,

            created_slot,

            treasury_bump,

            bump,
        }
    }
}

/// Custom struct: OrgMember
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OrgMember {
    pub org_id: u64,

    pub agent: Pubkey,

    pub role: u8,

    pub share_bps: u16,

    pub bump: u8,
}

impl OrgMember {
    pub fn new(org_id: u64, agent: Pubkey, role: u8, share_bps: u16, bump: u8) -> Self {
        Self {
            org_id,

            agent,

            role,

            share_bps,

            bump,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
